name: MergedPullRequestTracker

on:
  pull_request:
    types: [opened,edited,closed]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: takuya-kikuchi/github-actions-trial@v5
      with:
        SOURCE_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
        REPOSITORY_OWNER_NAME: ${{ github.event.pull_request.base.repo.owner.login }}
        REPOSITORY_NAME: ${{ github.event.pull_request.base.repo.name }}
        MERGED_PR_NUMBER: ${{ github.event.pull_request.number }}
        MERGED_PR_TITLE: ${{ github.event.pull_request.title }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
